events { worker_connections 1024; }

http {
    server {
        listen 80;
        
        # Sécurité : On retire les headers qui donnent trop d'infos
        server_tokens off;
        add_header X-Content-Type-Options nosniff;

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api {
            proxy_pass http://api:5000;
        }
    }
}